update stand_types
set
  title = 'Multi-Link Stands',
  description = 'Branded stands that open a hosted Tap Rater page with multiple customer links.',
  short_description = 'Open multiple customer links from one branded NFC and QR stand.',
  long_content = 'Multi-Link stands open a hosted Tap Rater page so one branded stand can connect customers to review, menu, booking, social, website, offer, and other important links.',
  buyer_intent = 'For businesses that want one stand to open multiple important customer links.',
  seo_title = 'Multi-Link NFC Stands | Tap Rater',
  seo_description = 'Shop Multi-Link NFC and QR stands that open a hosted Tap Rater page with review, menu, booking, social, and website links.',
  image_url = '/uploads/products/visit-website-stand.png',
  updated_at = now()
where slug = 'website-link-stands';

update products
set
  slug = 'multi-link-stand',
  title = 'Multi-Link Stand',
  sku = 'TR-MULTILINK-STAND',
  stand_type_slug = 'website-link-stands',
  primary_platform_slug = null,
  destination_type = 'website',
  is_special_solution = false,
  product_kind = 'hosted_multilink',
  product_type = 'platform_landing_page',
  service_mode = 'hosted_landing_page',
  checkout_mode = 'subscription',
  requires_account = true,
  requires_subscription = true,
  requires_landing_page = true,
  supported_destinations = array['website', 'custom', 'google', 'facebook', 'yelp', 'tripadvisor', 'booking', 'menu', 'feedback']::text[],
  activation_type = 'premium_hosted_activation',
  included_service_label = 'Hosted Tap Rater page',
  customization_options = array['standard_design', 'add_logo']::text[],
  allows_logo_upload = true,
  allows_custom_design = false,
  design_mode = 'logo',
  display_text = 'Connect With Us',
  base_price_cents = 4900,
  short_description = 'Branded NFC and QR stand that opens a hosted Tap Rater page with multiple customer links.',
  description = 'Multi-Link Stand is a branded tabletop NFC and QR display that opens a hosted Tap Rater page. Use one stand for review links, menus, booking, social profiles, websites, offers, and other important customer actions.',
  images = '[{"src":"/uploads/products/visit-website-stand.png","alt":"Tap Rater Multi-Link Stand"}]'::jsonb,
  standard_angled_image_url = '/uploads/products/visit-website-stand.png',
  branded_angled_image_url = '/uploads/products/visit-website-stand-branded-angled.png',
  multilink_angled_image_url = '/uploads/products/visit-website-stand-branded-angled.png',
  branded_front_template_url = '/uploads/products/visit-website-stand-branded-front-template.png',
  multilink_front_template_url = '/uploads/products/visit-website-stand-branded-front-template.png',
  seo_title = 'Multi-Link Stand | Hosted NFC and QR Link Stand',
  seo_description = 'Buy a Multi-Link NFC and QR stand that opens a hosted Tap Rater page for review, menu, booking, social, website, and offer links.',
  search_keywords = array['multi-link stand', 'multilink nfc stand', 'qr multi link stand', 'hosted link stand']::text[],
  updated_at = now()
where slug = 'visit-our-website-stand'
  and not exists (select 1 from products where slug = 'multi-link-stand');

insert into products (
  slug,
  title,
  sku,
  category_slug,
  stand_type_slug,
  primary_platform_slug,
  destination_type,
  is_special_solution,
  product_kind,
  status,
  base_price_cents,
  stock_status,
  short_description,
  description,
  product_type,
  service_mode,
  checkout_mode,
  requires_account,
  requires_subscription,
  requires_landing_page,
  supported_destinations,
  activation_type,
  included_service_label,
  format,
  customization_options,
  allows_logo_upload,
  allows_custom_design,
  design_mode,
  display_text,
  images,
  standard_angled_image_url,
  branded_angled_image_url,
  multilink_angled_image_url,
  branded_front_template_url,
  multilink_front_template_url,
  seo_title,
  seo_description,
  search_keywords,
  asset_readiness_status,
  is_active
)
values (
  'multi-link-stand',
  'Multi-Link Stand',
  'TR-MULTILINK-STAND',
  'website-links',
  'website-link-stands',
  null,
  'website',
  false,
  'hosted_multilink',
  'active',
  4900,
  'instock',
  'Branded NFC and QR stand that opens a hosted Tap Rater page with multiple customer links.',
  'Multi-Link Stand is a branded tabletop NFC and QR display that opens a hosted Tap Rater page. Use one stand for review links, menus, booking, social profiles, websites, offers, and other important customer actions.',
  'platform_landing_page',
  'hosted_landing_page',
  'subscription',
  true,
  true,
  true,
  array['website', 'custom', 'google', 'facebook', 'yelp', 'tripadvisor', 'booking', 'menu', 'feedback']::text[],
  'premium_hosted_activation',
  'Hosted Tap Rater page',
  'stand',
  array['standard_design', 'add_logo']::text[],
  true,
  false,
  'logo',
  'Connect With Us',
  '[{"src":"/uploads/products/visit-website-stand.png","alt":"Tap Rater Multi-Link Stand"}]'::jsonb,
  '/uploads/products/visit-website-stand.png',
  '/uploads/products/visit-website-stand-branded-angled.png',
  '/uploads/products/visit-website-stand-branded-angled.png',
  '/uploads/products/visit-website-stand-branded-front-template.png',
  '/uploads/products/visit-website-stand-branded-front-template.png',
  'Multi-Link Stand | Hosted NFC and QR Link Stand',
  'Buy a Multi-Link NFC and QR stand that opens a hosted Tap Rater page for review, menu, booking, social, website, and offer links.',
  array['multi-link stand', 'multilink nfc stand', 'qr multi link stand', 'hosted link stand']::text[],
  'ready',
  true
)
on conflict (slug) do update
set
  title = excluded.title,
  sku = excluded.sku,
  category_slug = excluded.category_slug,
  stand_type_slug = excluded.stand_type_slug,
  primary_platform_slug = excluded.primary_platform_slug,
  destination_type = excluded.destination_type,
  is_special_solution = excluded.is_special_solution,
  product_kind = excluded.product_kind,
  status = excluded.status,
  base_price_cents = excluded.base_price_cents,
  stock_status = excluded.stock_status,
  short_description = excluded.short_description,
  description = excluded.description,
  product_type = excluded.product_type,
  service_mode = excluded.service_mode,
  checkout_mode = excluded.checkout_mode,
  requires_account = excluded.requires_account,
  requires_subscription = excluded.requires_subscription,
  requires_landing_page = excluded.requires_landing_page,
  supported_destinations = excluded.supported_destinations,
  activation_type = excluded.activation_type,
  included_service_label = excluded.included_service_label,
  format = excluded.format,
  customization_options = excluded.customization_options,
  allows_logo_upload = excluded.allows_logo_upload,
  allows_custom_design = excluded.allows_custom_design,
  design_mode = excluded.design_mode,
  display_text = excluded.display_text,
  images = excluded.images,
  standard_angled_image_url = excluded.standard_angled_image_url,
  branded_angled_image_url = excluded.branded_angled_image_url,
  multilink_angled_image_url = excluded.multilink_angled_image_url,
  branded_front_template_url = excluded.branded_front_template_url,
  multilink_front_template_url = excluded.multilink_front_template_url,
  seo_title = excluded.seo_title,
  seo_description = excluded.seo_description,
  search_keywords = excluded.search_keywords,
  asset_readiness_status = excluded.asset_readiness_status,
  is_active = excluded.is_active,
  updated_at = now();

update product_options
set is_active = false, updated_at = now()
where product_slug in ('visit-our-website-stand', 'multi-link-stand')
  and option_code in ('standard_direct', 'branded_qr_direct');

insert into product_options (
  product_slug,
  option_code,
  title,
  description,
  price_cents,
  monthly_price_cents,
  max_links,
  requires_destination_url,
  has_qr,
  requires_logo,
  requires_business_name,
  requires_design_step,
  requires_front_proof,
  requires_subscription,
  account_required,
  supports_reorderable_links,
  supports_link_visibility,
  landing_page_url_pattern,
  footer_label,
  is_active,
  sort_order
)
values (
  'multi-link-stand',
  'hosted_multilink',
  'Hosted Multi-Link Stand',
  'Branded stand connected to a hosted Tap Rater page with up to 10 managed links.',
  4900,
  990,
  10,
  false,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  'https://taprater.com/p/{code}',
  'Powered by Tap Rater',
  true,
  30
)
on conflict (product_slug, option_code) do update
set
  title = excluded.title,
  description = excluded.description,
  price_cents = excluded.price_cents,
  monthly_price_cents = excluded.monthly_price_cents,
  max_links = excluded.max_links,
  requires_destination_url = excluded.requires_destination_url,
  has_qr = excluded.has_qr,
  requires_logo = excluded.requires_logo,
  requires_business_name = excluded.requires_business_name,
  requires_design_step = excluded.requires_design_step,
  requires_front_proof = excluded.requires_front_proof,
  requires_subscription = excluded.requires_subscription,
  account_required = excluded.account_required,
  supports_reorderable_links = excluded.supports_reorderable_links,
  supports_link_visibility = excluded.supports_link_visibility,
  landing_page_url_pattern = excluded.landing_page_url_pattern,
  footer_label = excluded.footer_label,
  is_active = excluded.is_active,
  sort_order = excluded.sort_order,
  updated_at = now();
