/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: ebf15c5cb64482640a1883ecd40e4cc6)
interface __BaseEnv_CloudflareEnv {
	PRODUCT_MEDIA_BUCKET: R2Bucket;
	HOSTED_PAGE_SNAPSHOTS: R2Bucket;
	PUBLIC_FORM_RATE_LIMITER: RateLimit;
	PUBLIC_CHECKOUT_RATE_LIMITER: RateLimit;
	PUBLIC_EVENT_RATE_LIMITER: RateLimit;
	ASSETS: Fetcher;
	NEXT_PUBLIC_ACCOUNT_APP_URL: string;
	PRODUCT_MEDIA_PUBLIC_BASE_URL: string;
	STRIPE_MODE: string;
	STRIPE_BILLING_PORTAL_CONFIGURED: string;
	STRIPE_CUSTOMER_EMAILS_CONFIGURED: string;
	TAP_RATER_ENABLE_PRODUCTION_HOSTED_PAGES: string;
	TAP_RATER_ENABLE_HOSTED_PURCHASING: string;
	NEXT_PUBLIC_SITE_URL: string;
	ADMIN_EMAIL: string;
	ADMIN_PASSWORD: string;
	ADMIN_SESSION_SECRET: string;
	DATABASE_URL: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./custom-worker");
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends Partial<StringifyValues<Pick<Cloudflare.Env, "NEXT_PUBLIC_ACCOUNT_APP_URL" | "PRODUCT_MEDIA_PUBLIC_BASE_URL" | "STRIPE_MODE" | "STRIPE_BILLING_PORTAL_CONFIGURED" | "STRIPE_CUSTOMER_EMAILS_CONFIGURED" | "TAP_RATER_ENABLE_PRODUCTION_HOSTED_PAGES" | "TAP_RATER_ENABLE_HOSTED_PURCHASING" | "NEXT_PUBLIC_SITE_URL" | "ADMIN_EMAIL" | "ADMIN_PASSWORD" | "ADMIN_SESSION_SECRET" | "DATABASE_URL">>> {}
}
